# TODO: account<->signer must be a many-to-many relationship
type Account {
  id: String!
  signers: Signer
}

type Signer {
  id: String!
}

type ChallengePeriod {
  id: String!
  account: Account!
  issuer: Signer!
  reason: String!
  deadline: String!
  isClosed: String!
}

type Health {
  id: String!
  synced_block: String!
}
